export * from './Home/Home';
export * from './Contact/Contact';
export * from './Plots/Plots';
export * from './Endoresments/Endoresments';
export * from './About/About';
export * from './CustomerData/Customerdata';
export * from './Login/Login';
export * from './UpdateData/UpdateData';
export * from './Registeration/Register';